version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_leantime
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '321.qwerty'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '321.qwerty'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 33070:3306
    expose:
        - 33070
  web:
    image: leantime/leantime:latest
    volumes:
      - ".:/var/www/html"
    container_name: leantime
    environment:
      LEAN_DB_HOST: 'mysql_leantime'
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: '321.qwerty'
      LEAN_DB_DATABASE: 'leantime'

    ports:
      - "8090:80"
    depends_on:
      - db
volumes:
  db_data: {}